spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/db.changelog-master.yml'
    contexts: dev
    drop-first: false
    default-schema: public
    liquibase-schema: public
    database-change-log-lock-table: 'databasechangeloglock'
    database-change-log-table: 'databasechangelog'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_NAME}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
myapp:
  secret-key: ${SECRET_KEY}
  upload-path: ${UPLOAD_PATH}
