spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rent_car
    username: postgres
    password: 1305
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/db.changelog-master.yml'
    contexts: dev
    drop-first: false
    default-schema: public
    liquibase-schema: public
    database-change-log-lock-table: 'databasechangeloglock'
    database-change-log-table: 'databasechangelog'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 9090
myapp:
  secret-key: 'c0388696-55b0-479c-a142-a2ae7cbe269a'